################################################################################
####################             Project Euler              ####################
####################               Problem 2                ####################
####################         Even Fibonacci numbers         ####################
####################                                        ####################
####################    Solved by R by Lubomir Stepanek     ####################
####################             March 11, 2018             ####################
################################################################################

# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms. -----------


## -----------------------------------------------------------------------------

################################################################################

## If we take a closer look at Fibonacci sequence, we can notice that
## the second one and then every third number in sequence

##     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

## is even, i. e. the sequence

##     2, 8, 34, 144, 610, 2584, ...

## of even numbers follows the following recursive formula

##     EF_{n} = 4 EF_{n-1} + EF_{n-2}

## with seed values EF_{1} = 2 and EF_{2} = 8.

## Let us take a look original Fibonacci Formula and write it in the
## form of F_{n-3} and F_{n-6} because of the fact that the second one and then
## every third Fibinacci number is even:

##     F_{n} = F_{n-1} + F_{n-2}                 // expanding both terms
##           = F_{n-2} + F_{n-3} + F_{n-3} + F_{n-4} 
##           = F_{n-2} + 2 F_{n-3} + F_{n-4}     // expending first term
##           = F_{n-3} + F_{n-4} + 2 F_{n-3} + F_{n-4}
##           = 3 F_{n-3} + 2 F_{n-4}             // expending one F_{n-4}
##           = 3 F_{n-3} + F_{n-4} + F_{n-5} + F_{n-6}
##                                               // combing F_{n-4} and F_{n-5}
##           = 4 F_{n-3} + F_{n-6}  

## Since the second one and then every third Fibonacci Number is even, so if
## F_{n} is even then F_{n-3} is even and F_{n-6} is also even. Let F_{n} be
## x-th even element and mark it as EF_{x}.

## If F_{n} is EF_{x}, then F_{n-3} is previous even number, i.e. EF_{x-1}
## and F_{n-6} is previous of EF_{x-1}, i.e. EF_{x-2}

## So F_{n} = 4 F_{n-3} + F_{n-6}, which means EF_{x} = 4 EF_{x-1} + EF_{x-2}.


## -----------------------------------------------------------------------------

################################################################################

## my solution using R ---------------------------------------------------------

EF_1 <- 2
EF_2 <- 8

my_fibonacci_sequence <- c(EF_1, EF_2)

while(
    4 * my_fibonacci_sequence[length(my_fibonacci_sequence)] +
    my_fibonacci_sequence[length(my_fibonacci_sequence) - 1] < 4000000
){
    
    my_fibonacci_sequence <- c(
        
        my_fibonacci_sequence,
        4 * my_fibonacci_sequence[length(my_fibonacci_sequence)] +
        my_fibonacci_sequence[length(my_fibonacci_sequence) - 1]
        
    )
    
}

sum(my_fibonacci_sequence)   # 4613732


## -----------------------------------------------------------------------------

################################################################################
################################################################################
################################################################################





