################################################################################
####################             Project Euler              ####################
####################               Problem 12               ####################
####################   Highly divisible triangular number   ####################
####################                                        ####################
####################    Solved by R by Lubomir Stepanek     ####################
####################            December 9, 2018            ####################
################################################################################

# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:

#     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred
# divisors?


## -----------------------------------------------------------------------------

################################################################################

## my solution using R ---------------------------------------------------------

getMyDivisors <- function(
    
    x
    
){
    
    # '''
    # Returns all positive integer divisors of a natural number "x".
    # '''
    
    return(
        c(1:x)[x %% c(1:x) == 0]
    )
    
}


## -----------------------------------------------------------------------------

n <- 500
i <- 1
x <- 1

while(length(getMyDivisors(x)) <= n){
    
    i <- i + 1
    x <- x + i
    
    flush.console()
    print("################################################################")
    print(
        paste(
            "i = ",
            i,
            " | ",
            "x = ",
            x,
            " | ",
            "# of divisors = ",
            length(getMyDivisors(x)),
            sep = ""
        )
    )
    
}

print(
    x
)   # 76576500


## -----------------------------------------------------------------------------

################################################################################
################################################################################
################################################################################





